from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ..entities.location import Location


class LocationRepository(Protocol):
    async def get_by_id(self, location_id: UUID) -> Location | None: ...
    async def list_all(self, active_only: bool = False) -> list[Location]: ...
    async def save(self, location: Location) -> Location: ...
    async def update(self, location: Location) -> Location: ...
    async def soft_delete(self, location_id: UUID) -> bool: ...
