from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ..entities.processing_rule import ProcessingRule


class ProcessingRuleRepository(Protocol):
    async def get_by_id(self, rule_id: UUID) -> ProcessingRule | None: ...
    async def list_active(self) -> list[ProcessingRule]: ...
    async def list_all(self) -> list[ProcessingRule]: ...
    async def save(self, rule: ProcessingRule) -> ProcessingRule: ...
    async def update(self, rule: ProcessingRule) -> ProcessingRule: ...
    async def delete(self, rule_id: UUID) -> bool: ...
